version: "3.8"
services:
  backend:
    build:
      context: ./healph-backend/
      dockerfile: ./Dockerfile
    container_name: healph-backend
    image: node:16.20.0-alpine
    #restart: always
    ports:
      - "3000:3000"
    working_dir: /healph-backend/
    entrypoint: ["npm", "start"]
    networks:
      - healph-net

networks:
  healph-net:
    driver: bridge


#docker-compose build
#docker-compose up
